name: CI/CD
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint (Ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv (+ Python 3.12)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Ruff check
        run: uvx ruff check --output-format=github .

  deploy:
    name: Deploy (Docker Compose on self-hosted)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ci]
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show runner info (sanity check)
        run: |
          uname -a || true
          docker --version || true
          (docker compose version || docker-compose --version) || true
      - name: Build & (re)start stack via Docker Compose
        env:
          DOCKER_BUILDKIT: "0"
          COMPOSE_DOCKER_CLI_BUILD: "1"
        run: |
          set -e
          