name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-and-build:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install Ruff
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # Step 4: Run Ruff linter
      - name: Ruff check
        run: ruff check --output-format=github .

      # Step 5: Build Docker images
      - name: Build Backend Docker
        run: docker build -t my-backend:latest ./backend

      - name: Build Frontend Docker
        run: docker build -t my-frontend:latest ./frontend

      # Step 6: Push Docker images (optional if using Docker Hub or private registry)
      # - name: Push Backend
      #   run: docker push my-backend:latest
      # - name: Push Frontend
      #   run: docker push my-frontend:latest

      # Step 7: Deploy services
      - name: Deploy Backend
        run: |
          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend -p 8000:8000 my-backend:latest

      - name: Deploy Frontend
        run: |
          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 8501:8501 my-frontend:latest
