name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-and-build:
    runs-on: self-hosted
    steps:
      # checkout repo
      - uses: actions/checkout@v4

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install Ruff
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # Run Ruff linter
      - name: Ruff check
        run: ruff check --output-format=github .

      # Build Docker images
      - name: Build Backend Docker
        run: docker build -t my-backend:latest ./backend

      - name: Build Frontend Docker
        run: docker build -t my-frontend:latest ./frontend

     

      # Deploy services
      - name: Deploy Backend
        run: |
          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend -p 8000:8000 my-backend:latest

      - name: Deploy Frontend
        run: |
          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 8501:8501 my-frontend:latest
