on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # Install uv and set Python (pin or read from your repo)
      - name: Setup uv (+ Python 3.13)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
          enable-cache: true

      # Lint with Ruff via uvx; show GitHub annotations on PRs
      - name: Ruff check
        run: uvx ruff check --output-format=github .

    